version: 1
formatters:
  simple:
    format: '%(asctime)s %(levelname)-8s %(name)-12s %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
  verbose:
    format: '%(asctime)s.%(msecs)03d %(levelname)-8s [%(module)s | %(funcName)s]  %(message)s'
    datefmt: '%y%m%dT%H%M%S'
handlers:
  # Console handler
  console:
    class : logging.StreamHandler
    formatter: simple
    level   : DEBUG
    stream  : ext://sys.stdout
  # File handlers
  file:
    class : logging.FileHandler
    formatter: simple
    level: INFO
    filename: Autotrader
loggers:
  alpaca:
    level: DEBUG
    handlers: [console, file]
    propagate: no
root:
  level: INFO
  handlers: [console, file]