# Allows the user to specify the directory in which the MarketStore database resides
root_directory: data
# Port that MarketStore will serve through for JSON-RPC API
listen_port: 5993
# Allows the user to specify the log level
log_level: debug
# Allows the user to run MarketStore in polling-only mode, where it will not respond to query
queryable: true
#Sets the amount of time MarketStore will wait to shutdown after a SIGINT signal is received
stop_grace_period: 0
#Frequency (in minutes) at which the WAL file will be trimmed after being flushed to disk
wal_rotate_interval: 5
# Threshold (in days) by which MarketStore will declare a symbol stale
stale_threshold: 5
enable_last_known: false
# System timezone by name of TZ database (e.g. America/New_York)
timezone: "America/New_York"
# List of trigger plugins
triggers:
  - module: ondiskagg.so
    # The file glob pattern to match on
    on: "*/1Min/OHLCV"
    config:
      destinations:
        - 3Min
        - 5Min
        - 15Min
        - 30Min
        - 1H
        - 2H
        - 1D
  - module: stream.so
    on: "*/*/*"
